### ISSUE TITLE
Initial embedded onboarding redirects to hosted UI

### ISSUE THREAD

**Issue by msn444** [stripe/stripe-connect-furever-demo#175]
The docs for Embedded Onboarding states "your connected accounts interact with the embedded component without ever leaving your application". Yet in the Furever demo, and my own experience, the `account-onboarding` component simply launches a new tab with a Stripe-hosted onboarding flow, which collects the email address and phone number. It then returns to the app to complete the rest of the flow, embedded as it should be.

Is it not possible to embed the "Let's get started" part of the onboarding?

**Comment by jorgea-stripe** [comment]
Responded in https://github.com/stripe/connect-js/issues/124. This isn't specific to Furever!
